CREATE TYPE public.app_role AS ENUM ('admin');
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL, role public.app_role NOT NULL, UNIQUE(user_id, role));
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read own role" ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role) $$;
CREATE TABLE public.publications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, description text NOT NULL DEFAULT '', cover_image text NOT NULL, pdf_file text NOT NULL, issue_date date NOT NULL, category text NOT NULL DEFAULT 'Monthly newspaper', created_at timestamptz NOT NULL DEFAULT now(), status text NOT NULL DEFAULT 'published' CHECK (status IN ('published','archived')), page_count integer NOT NULL DEFAULT 1, created_by uuid NOT NULL);
GRANT SELECT ON public.publications TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.publications TO authenticated;
GRANT ALL ON public.publications TO service_role;
ALTER TABLE public.publications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Published editions visible" ON public.publications FOR SELECT TO anon, authenticated USING(status = 'published');
CREATE POLICY "Editors read all editions" ON public.publications FOR SELECT TO authenticated USING(public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Editors publish editions" ON public.publications FOR INSERT TO authenticated WITH CHECK(public.has_role(auth.uid(), 'admin') AND created_by = auth.uid());
CREATE POLICY "Editors update editions" ON public.publications FOR UPDATE TO authenticated USING(public.has_role(auth.uid(), 'admin')) WITH CHECK(public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Editors delete editions" ON public.publications FOR DELETE TO authenticated USING(public.has_role(auth.uid(), 'admin'));
CREATE INDEX publications_issue_date_idx ON public.publications(issue_date DESC, created_at DESC);
CREATE POLICY "Editors upload publication files" ON storage.objects FOR INSERT TO authenticated WITH CHECK(bucket_id IN ('publication-covers','publication-pdfs') AND public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Editors manage publication files" ON storage.objects FOR DELETE TO authenticated USING(bucket_id IN ('publication-covers','publication-pdfs') AND public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Published PDF reads and editor reads" ON storage.objects FOR SELECT TO anon, authenticated USING(bucket_id = 'publication-pdfs' AND (EXISTS (SELECT 1 FROM public.publications WHERE pdf_file = name AND status = 'published') OR public.has_role(auth.uid(), 'admin')));
CREATE POLICY "Cover reads" ON storage.objects FOR SELECT TO anon, authenticated USING(bucket_id = 'publication-covers');